Repository graphql-java/graphql-java, pull requests merged in 2018-08, with the labels that each got.

#1113 Fix NPE in FieldLevelTrackingApproach when type mismatch error
  src/main/java/graphql/execution/AsyncExecutionStrategy.java
  src/main/java/graphql/execution/FieldValueInfo.java
  src/test/groovy/graphql/execution/AsyncExecutionStrategyTest.groovy
  src/test/groovy/graphql/execution/FieldValueInfoTest.groovy
  src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderTypeMismatchTest.groovy
Labels: stablefix

#1150 fix: #1147 ClassCastException in schema generation
  src/main/java/graphql/schema/idl/SchemaGenerator.java
  src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
Labels: stablefix

#1161 stable branch cherry pick of 1113
  src/main/java/graphql/execution/AsyncExecutionStrategy.java
  src/main/java/graphql/execution/FieldValueInfo.java
  src/test/groovy/graphql/execution/AsyncExecutionStrategyTest.groovy
  src/test/groovy/graphql/execution/FieldValueInfoTest.groovy
  src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderTypeMismatchTest.groovy
Labels: stablebackport

#1162 stable fix of PR 1141
  src/main/java/graphql/util/Traverser.java
  src/test/groovy/graphql/util/TraverserTest.groovy
Labels: stablebackport

#1163 Stable fix of pr 1150
  src/main/java/graphql/schema/idl/SchemaGenerator.java
  src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
Labels: stablebackport

#1191 BB patch of Fix race condition dispatch in FieldLevelTrackingApproach
  src/main/java/graphql/execution/instrumentation/dataloader/FieldLevelTrackingApproach.java
  src/test/groovy/graphql/execution/instrumentation/dataloader/Issue1178DataLoaderDispatchTest.groovy
Labels: stable fix

#1196 Forwardport of pr 1159
  src/main/java/graphql/language/AstValueHelper.java
  src/test/groovy/graphql/language/AstValueHelperTest.groovy
Labels: stable fix
