Repository graphql-java/graphql-java, pull requests merged in 2019-03, with the labels that each got.

#1427 Made the ErrorType implement a base interface
  src/main/java/graphql/ErrorClassification.java
  src/main/java/graphql/ErrorType.java
  src/main/java/graphql/GraphQLError.java
  src/main/java/graphql/GraphqlErrorBuilder.java
  src/main/java/graphql/execution/AbsoluteGraphQLError.java
Labels: breaking change

#1455 fix test batching test: relax condition because we can't guarantee just one batch call
  src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderPerformanceTest.groovy
Labels: not release related

#1456 fix batching test: relax condition because we can't guarantee just one batch call
  src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderPerformanceTest.groovy
Labels: not release related

#1452 Exponents can have positive exponents
  src/main/antlr/GraphqlCommon.g4
  src/test/groovy/graphql/parser/ParserTest.groovy
Labels: needs to be backported

#1460 Removed @defer as a default directive
  src/main/java/graphql/Directives.java
  src/main/java/graphql/schema/GraphQLSchema.java
  src/test/groovy/graphql/StarWarsIntrospectionTests.groovy
  src/test/groovy/graphql/execution/defer/DeferSupportIntegrationTest.groovy
  src/test/groovy/graphql/schema/GraphQLSchemaTest.groovy
Labels: breaking change

#1462 Backport the #1438 buf to 9x
  src/main/java/graphql/parser/StringValueParsing.java
  src/test/groovy/graphql/parser/StringValueParsingTest.groovy
Labels: stable fix

#1469 non null directive args with defaults can be missing bug
  src/main/java/graphql/validation/rules/ProvidedNonNullArguments.java
  src/test/groovy/graphql/validation/rules/ProvidedNonNullArgumentsTest.groovy
Labels: needs to be backported

#1471 non null directive args with defaults can be missing - backport
  src/main/java/graphql/validation/rules/ProvidedNonNullArguments.java
  src/test/groovy/graphql/validation/rules/ProvidedNonNullArgumentsTest.groovy
Labels: stable fix
