Repository graphql-java/graphql-java, pull requests merged in 2020-05, with the labels that each got.

#1891 refactor ExecutionPath to improve performance and simplify it
  src/main/java/graphql/execution/ExecutionPath.java
  src/test/groovy/graphql/execution/ExecutionPathTest.groovy
Labels: breaking change

#1903 remove flags on GraphQLDirective
  src/main/java/graphql/introspection/Introspection.java
  src/main/java/graphql/schema/GraphQLDirective.java
  src/main/java/graphql/validation/rules/KnownDirectives.java
  src/test/groovy/graphql/TestUtil.groovy
Labels: breaking change

#1792 This reduces the memory overhead of NonNullableFieldWasNullException …
  src/main/java/graphql/GraphQLException.java
  src/main/java/graphql/analysis/FieldComplexityEnvironment.java
  src/main/java/graphql/analysis/QueryVisitorFieldArgumentEnvironmentImpl.java
  src/main/java/graphql/analysis/QueryVisitorFieldArgumentInputValueImpl.java
  src/main/java/graphql/analysis/QueryVisitorFieldEnvironmentImpl.java
  src/main/java/graphql/execution/ExecutionStepInfo.java
  src/main/java/graphql/execution/NonNullableFieldWasNullException.java
Labels: needs to be backported

#1797 add missing WiringFactory methods to CombinedWiringFactory
  src/main/java/graphql/schema/idl/CombinedWiringFactory.java
  src/test/groovy/graphql/schema/idl/WiringFactoryTest.groovy
Labels: needs to be backported

#1821 Fixed a copy pasta bug from #1818
  src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
  src/test/groovy/graphql/schema/DataFetchingEnvironmentImplTest.groovy
Labels: needs to be backported

#1907 Merged conflict of 1798 Saponniah fix schema printer no fields
  src/main/java/graphql/schema/idl/SchemaPrinter.java
  src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy
Labels: needs to be backported

#1801 This fixes the Subscription publisher so that it does not drop values…
  src/main/java/graphql/execution/reactive/CompletionStageMappingPublisher.java
  src/test/groovy/graphql/execution/pubsub/CapturingSubscriber.java
  src/test/groovy/graphql/execution/reactive/CompletionStageMappingPublisherTest.groovy
Labels: needs to be backported

#1836 Fixes a stack over flow problem in the validation rules
  src/main/java/graphql/validation/Validator.java
  src/main/java/graphql/validation/rules/DeferredMustBeOnAllFields.java
  src/test/groovy/graphql/TestUtil.groovy
  src/test/groovy/graphql/validation/rules/NoFragmentCyclesTest.groovy
Labels: needs to be backported

#1846 #1845: Implemented optimized FieldCoordinates creation methods
  src/main/java/graphql/schema/FieldCoordinates.java
  src/main/java/graphql/schema/GraphQLCodeRegistry.java
  src/test/groovy/graphql/schema/FieldCoordinatesTest.groovy
Labels: needs to be backported

#1864 1847: Fix circular reference between input object field/type
  src/main/java/graphql/schema/GraphQLInputObjectField.java
  src/test/groovy/graphql/Issue1847.groovy
Labels: needs to be backported

#1904 Stable fix of pr 1792
  src/main/java/graphql/GraphQLException.java
  src/main/java/graphql/analysis/FieldComplexityEnvironment.java
  src/main/java/graphql/analysis/QueryVisitorFieldArgumentEnvironmentImpl.java
  src/main/java/graphql/analysis/QueryVisitorFieldArgumentInputValueImpl.java
  src/main/java/graphql/analysis/QueryVisitorFieldEnvironmentImpl.java
  src/main/java/graphql/execution/ExecutionStepInfo.java
  src/main/java/graphql/execution/NonNullableFieldWasNullException.java
Labels: stable fix PR

#1905 stable fix port of 1797
  src/main/java/graphql/schema/idl/CombinedWiringFactory.java
  src/test/groovy/graphql/schema/idl/WiringFactoryTest.groovy
Labels: stable fix PR

#1906 Fixed a copy pasta bug from #1818 (#1821)
  src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
  src/test/groovy/graphql/schema/DataFetchingEnvironmentImplTest.groovy
Labels: stable fix PR

#1908 stable fix of pr 1907
  src/main/java/graphql/schema/idl/SchemaPrinter.java
  src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy
Labels: stable fix PR

#1909 Stable backport of 1801
  src/main/java/graphql/execution/reactive/CompletionStageMappingPublisher.java
  src/test/groovy/graphql/execution/pubsub/CapturingSubscriber.java
  src/test/groovy/graphql/execution/reactive/CompletionStageMappingPublisherTest.groovy
Labels: stable fix PR

#1910 #1845: Implemented optimized FieldCoordinates creation methods (#1846)
  src/main/java/graphql/schema/FieldCoordinates.java
  src/main/java/graphql/schema/GraphQLCodeRegistry.java
  src/test/groovy/graphql/schema/FieldCoordinatesTest.groovy
Labels: stable fix PR

#1911 1847: Fix circular reference between input object field/type (#1864)
  src/main/java/graphql/schema/GraphQLInputObjectField.java
  src/test/groovy/graphql/Issue1847.groovy
Labels: stable fix PR

#1924 add test for local context and aliases
  src/test/groovy/graphql/LocalContextTest.groovy
Labels: not release related
