Repository graphql-java/graphql-java, pull requests merged in 2023-06, with the labels that each got.

#3236 Minor performance fixes
  src/main/java/graphql/execution/AbstractAsyncExecutionStrategy.java
  src/main/java/graphql/execution/AsyncExecutionStrategy.java
  src/main/java/graphql/execution/ExecutionStepInfoFactory.java
  src/main/java/graphql/execution/ExecutionStrategy.java
  src/main/java/graphql/execution/ExecutionStrategyParameters.java
Labels: performance

#3235 This avoids a CF allocation on data fetcher in the main case where there is no exception
  src/main/java/graphql/execution/ExecutionStrategy.java
Labels: breaking change, performance

#3231 Removing the deprecated CacheControl support
  src/main/java/graphql/ExecutionInput.java
  src/main/java/graphql/cachecontrol/CacheControl.java
  src/main/java/graphql/execution/Execution.java
  src/main/java/graphql/execution/ExecutionContext.java
  src/main/java/graphql/execution/ExecutionContextBuilder.java
  src/main/java/graphql/schema/DataFetchingEnvironment.java
  src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
  src/main/java/graphql/schema/DelegatingDataFetchingEnvironment.java
  src/test/groovy/graphql/cachecontrol/CacheControlTest.groovy
Labels: breaking change
