Repository graphql-java/graphql-java, pull requests merged in 2024-02, with the labels that each got.

#3330 ExecutionResult wrapping can be avoided - reduces memory allocations and GC
  src/main/java/graphql/execution/AbstractAsyncExecutionStrategy.java
  src/main/java/graphql/execution/AsyncExecutionStrategy.java
  src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
  src/main/java/graphql/execution/ExecutionStrategy.java
  src/main/java/graphql/execution/FieldValueInfo.java
  src/main/java/graphql/execution/SubscriptionExecutionStrategy.java
  src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java
  src/main/java/graphql/execution/instrumentation/ExecuteObjectInstrumentationContext.java
  src/main/java/graphql/execution/instrumentation/Instrumentation.java
  src/main/java/graphql/execution/instrumentation/NoContextChainedInstrumentation.java
  src/main/java/graphql/execution/instrumentation/SimplePerformantInstrumentation.java
  src/main/java/graphql/execution/instrumentation/adapters/ExecuteObjectInstrumentationContextAdapter.java
  src/main/java/graphql/execution/instrumentation/adapters/ExecutionResultInstrumentationContextAdapter.java
  src/main/java/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherInstrumentation.java
  src/main/java/graphql/execution/instrumentation/dataloader/FieldLevelTrackingApproach.java
  src/test/groovy/graphql/execution/BreadthFirstExecutionTestStrategy.java
  src/test/groovy/graphql/execution/BreadthFirstTestStrategy.java
  src/test/groovy/graphql/execution/ExecutionStrategyErrorsTest.groovy
  src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy
  src/test/groovy/graphql/execution/FieldValueInfoTest.groovy
  src/test/groovy/graphql/execution/instrumentation/AllNullTestingInstrumentation.groovy
  src/test/groovy/graphql/execution/instrumentation/ChainedInstrumentationStateTest.groovy
  src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy
  src/test/groovy/graphql/execution/instrumentation/LegacyTestingInstrumentation.groovy
  src/test/groovy/graphql/execution/instrumentation/ModernTestingInstrumentation.groovy
  src/test/groovy/graphql/execution/instrumentation/NamedInstrumentation.groovy
  src/test/groovy/graphql/execution/instrumentation/NoContextChainedInstrumentationTest.groovy
  src/test/groovy/graphql/execution/instrumentation/TestingExecuteObjectInstrumentationContext.groovy
  src/test/groovy/graphql/execution/preparsed/PreparsedDocumentProviderTest.groovy
Labels: breaking change

#3447 Native DataLoader dispatch strategy without Instrumentation
  src/main/java/graphql/ExecutionInput.java
  src/main/java/graphql/GraphQL.java
  src/main/java/graphql/execution/AsyncExecutionStrategy.java
  src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
  src/main/java/graphql/execution/DataLoaderDispatchStrategy.java
  src/main/java/graphql/execution/Execution.java
  src/main/java/graphql/execution/ExecutionContext.java
  src/main/java/graphql/execution/ExecutionStrategy.java
  src/main/java/graphql/execution/incremental/DeferredExecutionSupport.java
  src/main/java/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherInstrumentation.java
  src/main/java/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherInstrumentationOptions.java
  src/main/java/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherInstrumentationState.java
  src/main/java/graphql/execution/instrumentation/dataloader/EmptyDataLoaderRegistryInstance.java
  src/main/java/graphql/execution/instrumentation/dataloader/FallbackDataLoaderDispatchStrategy.java
  src/main/java/graphql/execution/instrumentation/dataloader/FieldLevelTrackingApproach.java
  src/main/java/graphql/execution/instrumentation/dataloader/LevelMap.java
  src/main/java/graphql/execution/instrumentation/dataloader/PerLevelDataLoaderDispatchStrategy.java
  src/test/groovy/example/http/HttpMain.java
  src/test/groovy/graphql/GraphQLTest.groovy
  src/test/groovy/graphql/Issue2068.groovy
  src/test/groovy/graphql/execution/ExecutionTest.groovy
  src/test/groovy/graphql/execution/instrumentation/ChainedInstrumentationStateTest.groovy
  src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy
  src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderCompanyProductMutationTest.groovy
  src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherTest.groovy
  src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderHangingTest.groovy
  src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderNodeTest.groovy
  src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderPerformanceData.groovy
  src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderPerformanceTest.groovy
  src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderPerformanceWithChainedInstrumentationTest.groovy
  src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderTypeMismatchTest.groovy
  src/test/groovy/graphql/execution/instrumentation/dataloader/Issue1178DataLoaderDispatchTest.groovy
  src/test/groovy/graphql/execution/instrumentation/dataloader/PeopleCompaniesAndProductsDataLoaderTest.groovy
  src/test/groovy/graphql/execution/instrumentation/fieldvalidation/FieldValidationTest.groovy
  src/test/groovy/readme/DataLoaderBatchingExamples.java
Labels: breaking change

#3467 Added Async benchmark for future changes
  src/test/java/benchmark/AsyncBenchmark.java
Labels: not release related

#3468 cleaning up the jhm benchmarks
  src/test/java/benchmark/AddError.java
  src/test/java/benchmark/AstPrinterBenchmark.java
  src/test/java/benchmark/AsyncBenchmark.java
  src/test/java/benchmark/ChainedInstrumentationBenchmark.java
  src/test/java/benchmark/CreateSchemaBenchmark.java
  src/test/java/benchmark/DFSelectionSetBenchmark.java
  src/test/java/benchmark/ENFBenchmark1.java
  src/test/java/benchmark/ENFBenchmark2.java
  src/test/java/benchmark/ENFExtraLargeBenchmark.java
  src/test/java/benchmark/GetterAccessBenchmark.java
  src/test/java/benchmark/IntMapBenchmark.java
  src/test/java/benchmark/IntrospectionBenchmark.java
  src/test/java/benchmark/ListBenchmark.java
  src/test/java/benchmark/NQBenchmark2.java
  src/test/java/benchmark/OverlappingFieldValidationBenchmark.java
  src/test/java/benchmark/PropertyFetcherBenchMark.java
  src/test/java/benchmark/SchemaTransformerBenchmark.java
  src/test/java/benchmark/SimpleQueryBenchmark.java
  src/test/java/benchmark/TwitterBenchmark.java
  src/test/java/benchmark/TypeDefinitionParserVersusSerializeBenchmark.java
  src/test/java/benchmark/ValidatorBenchmark.java
Labels: not release related

#3469 fixed async benchmark - it was nonsensical before
  src/test/java/benchmark/AsyncBenchmark.java
Labels: not release related, performance

#3472 andis suggestions on batch size
  src/test/java/benchmark/AsyncBenchmark.java
Labels: not release related, performance

#3476 Added a more complex query benchmark
  src/test/java/benchmark/ComplexQueryBenchmark.java
  src/test/resources/storesanddepartments.graphqls
Labels: not release related, performance

#3485 Now allows the benchmark to go into profiling mode
  src/test/java/benchmark/ComplexQueryBenchmark.java
Labels: not release related, performance

#3486 Now allows the benchmark to go into profiling mode - 2
  src/test/java/benchmark/ComplexQueryBenchmark.java
Labels: not release related, performance
