Repository graphql-java/graphql-java, pull requests merged in 2024-03, with the labels that each got.

#3465 Don't build a builder object and then turn it into the actual object
  src/main/java/graphql/execution/ExecutionStrategy.java
  src/main/java/graphql/execution/FetchedValue.java
  src/main/java/graphql/execution/FieldValueInfo.java
  src/test/groovy/graphql/execution/FieldValueInfoTest.groovy
Labels: breaking change, performance

#3387 directive filtering during printing
  src/main/java/graphql/schema/idl/SchemaPrinter.java
  src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy
  src/test/groovy/graphql/util/AnonymizerTest.groovy
Labels: breaking change

#3491 Updated helper code for profiler attachment
  src/test/java/benchmark/BenchmarkUtils.java
  src/test/java/benchmark/ComplexQueryBenchmark.java
Labels: not release related, performance

#3484 Does not allocate a default deferred context that is thrown away on transform
  src/main/java/graphql/execution/ExecutionStrategyParameters.java
Labels: performance

#3499 Get fieldDef improvements from Netflix
  src/main/java/graphql/execution/ExecutionStrategy.java
  src/main/java/graphql/execution/FieldCollector.java
  src/main/java/graphql/execution/MergedField.java
  src/main/java/graphql/execution/MergedSelectionSet.java
  src/main/java/graphql/schema/GraphQLInterfaceType.java
  src/main/java/graphql/schema/GraphQLObjectType.java
Labels: breaking change, performance

#3489 Intern field names
  src/main/java/graphql/GraphQL.java
  src/main/java/graphql/execution/AsyncExecutionStrategy.java
  src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
  src/main/java/graphql/execution/Execution.java
  src/main/java/graphql/execution/ExecutionStrategy.java
  src/main/java/graphql/execution/FetchedValue.java
  src/main/java/graphql/execution/FieldValueInfo.java
  src/main/java/graphql/execution/SubscriptionExecutionStrategy.java
  src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java
  src/main/java/graphql/execution/instrumentation/ExecuteObjectInstrumentationContext.java
  src/main/java/graphql/execution/instrumentation/ExecutionStrategyInstrumentationContext.java
  src/main/java/graphql/execution/instrumentation/InstrumentationContext.java
  src/main/java/graphql/execution/instrumentation/SimpleInstrumentationContext.java
  src/main/java/graphql/execution/instrumentation/adapters/ExecuteObjectInstrumentationContextAdapter.java
  src/main/java/graphql/execution/instrumentation/adapters/ExecutionResultInstrumentationContextAdapter.java
  src/main/java/graphql/language/Field.java
  src/main/java/graphql/schema/GraphQLFieldDefinition.java
  src/main/java/graphql/schema/GraphQLInterfaceType.java
  src/main/java/graphql/schema/GraphQLObjectType.java
  src/main/java/graphql/schema/idl/SchemaPrinter.java
  src/main/java/graphql/util/FieldNameInterner.java
  src/test/groovy/graphql/execution/AsyncExecutionStrategyTest.groovy
  src/test/groovy/graphql/execution/FieldValueInfoTest.groovy
  src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy
  src/test/groovy/graphql/execution/instrumentation/TestingInstrumentContext.groovy
  src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy
  src/test/groovy/graphql/util/AnonymizerTest.groovy
Labels: performance

#3488 Map benchmarks
  src/test/java/benchmark/MapBenchmark.java
Labels: not release related, performance

#3492 A CompleteableFuture benchmark
  src/test/java/benchmark/CompletableFuturesBenchmark.java
Labels: not release related, performance

#3518 Return empty singleton DirectivesHolder if directives are empty
  src/main/java/graphql/DirectivesUtil.java
  src/main/java/graphql/schema/GraphQLArgument.java
  src/main/java/graphql/schema/GraphQLEnumType.java
  src/main/java/graphql/schema/GraphQLEnumValueDefinition.java
  src/main/java/graphql/schema/GraphQLFieldDefinition.java
  src/main/java/graphql/schema/GraphQLInputObjectField.java
  src/main/java/graphql/schema/GraphQLInputObjectType.java
  src/main/java/graphql/schema/GraphQLInterfaceType.java
  src/main/java/graphql/schema/GraphQLObjectType.java
  src/main/java/graphql/schema/GraphQLScalarType.java
  src/main/java/graphql/schema/GraphQLUnionType.java
Labels: performance

#3504 Interning fieldnames (from netflix)
  src/main/java/graphql/language/Field.java
  src/main/java/graphql/schema/GraphQLFieldDefinition.java
  src/main/java/graphql/schema/GraphQLInterfaceType.java
  src/main/java/graphql/schema/GraphQLObjectType.java
  src/main/java/graphql/util/Interning.java
Labels: performance

#3508 Small tweaks to not allocate objects for lambda closures
  src/main/java/graphql/execution/ExecutionStepInfo.java
  src/main/java/graphql/execution/ExecutionStrategy.java
  src/main/java/graphql/execution/ValuesResolver.java
  src/main/java/graphql/schema/PropertyDataFetcherHelper.java
  src/main/java/graphql/schema/PropertyFetchingImpl.java
Labels: breaking change, performance

#3460 Removed the deprecated Instrumentation methods and removes ER wrapping
  src/main/java/graphql/GraphQL.java
  src/main/java/graphql/analysis/MaxQueryComplexityInstrumentation.java
  src/main/java/graphql/execution/Execution.java
  src/main/java/graphql/execution/SubscriptionExecutionStrategy.java
  src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java
  src/main/java/graphql/execution/instrumentation/Instrumentation.java
  src/main/java/graphql/execution/instrumentation/InstrumentationState.java
  src/main/java/graphql/execution/instrumentation/SimplePerformantInstrumentation.java
  src/main/java/graphql/execution/instrumentation/adapters/ExecuteObjectInstrumentationContextAdapter.java
  src/main/java/graphql/execution/instrumentation/adapters/ExecutionResultInstrumentationContextAdapter.java
  src/main/java/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherInstrumentation.java
  src/main/java/graphql/execution/instrumentation/parameters/InstrumentationExecuteOperationParameters.java
  src/main/java/graphql/execution/instrumentation/parameters/InstrumentationExecutionParameters.java
  src/main/java/graphql/execution/instrumentation/parameters/InstrumentationExecutionStrategyParameters.java
  src/main/java/graphql/execution/instrumentation/parameters/InstrumentationFieldCompleteParameters.java
  src/main/java/graphql/execution/instrumentation/parameters/InstrumentationFieldFetchParameters.java
  src/main/java/graphql/execution/instrumentation/parameters/InstrumentationFieldParameters.java
  src/main/java/graphql/execution/instrumentation/parameters/InstrumentationValidationParameters.java
  src/main/java/graphql/execution/instrumentation/tracing/TracingInstrumentation.java
  src/test/groovy/graphql/GraphQLTest.groovy
  src/test/groovy/graphql/analysis/MaxQueryComplexityInstrumentationTest.groovy
  src/test/groovy/graphql/analysis/MaxQueryDepthInstrumentationTest.groovy
  src/test/groovy/graphql/execution/SubscriptionExecutionStrategyTest.groovy
  src/test/groovy/graphql/execution/instrumentation/AllNullTestingInstrumentation.groovy
  src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy
  src/test/groovy/graphql/execution/instrumentation/LegacyTestingInstrumentation.groovy
  src/test/groovy/graphql/execution/instrumentation/ModernTestingInstrumentation.groovy
  src/test/groovy/graphql/execution/instrumentation/NamedInstrumentation.groovy
  src/test/groovy/graphql/execution/instrumentation/fieldvalidation/FieldValidationTest.groovy
  src/test/groovy/readme/InstrumentationExamples.java
  src/test/java/benchmark/ChainedInstrumentationBenchmark.java
Labels: breaking change

#3509 Removed deprecated methods in parsing
  src/main/java/graphql/parser/Parser.java
  src/test/groovy/graphql/parser/ParserExceptionTest.groovy
  src/test/groovy/graphql/parser/SDLParserTest.groovy
Labels: breaking change

#3510 Removed deprecated methods in doc providers
  src/main/java/graphql/execution/preparsed/NoOpPreparsedDocumentProvider.java
  src/main/java/graphql/execution/preparsed/PreparsedDocumentProvider.java
  src/main/java/graphql/execution/preparsed/persisted/InMemoryPersistedQueryCache.java
  src/main/java/graphql/execution/preparsed/persisted/PersistedQueryCache.java
  src/main/java/graphql/execution/preparsed/persisted/PersistedQuerySupport.java
  src/test/groovy/graphql/execution/preparsed/NoOpPreparsedDocumentProviderTest.groovy
  src/test/groovy/graphql/execution/preparsed/PreparsedDocumentProviderTest.groovy
  src/test/groovy/graphql/execution/preparsed/TestingPreparsedDocumentProvider.groovy
  src/test/groovy/graphql/execution/preparsed/persisted/ApolloPersistedQuerySupportTest.groovy
  src/test/groovy/graphql/execution/preparsed/persisted/InMemoryPersistedQueryCacheTest.groovy
Labels: breaking change

#3511 Removed deprecated methods in ExecutionInput
  src/main/java/graphql/ExecutionInput.java
  src/test/groovy/graphql/ExecutionInputTest.groovy
Labels: breaking change

#3512 Removed deprecated methods in ExecutionContext
  src/main/java/graphql/execution/ExecutionContext.java
  src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
  src/test/groovy/graphql/execution/ExecutionContextBuilderTest.groovy
Labels: breaking change

#3515 Removed deprecated methods in GraphQLSchema
  src/main/java/graphql/schema/GraphQLSchema.java
  src/main/java/graphql/validation/TraversalContext.java
  src/test/groovy/graphql/schema/visibility/GraphqlFieldVisibilityTest.groovy
Labels: breaking change

#3516 Removed deprecated methods and SchemaGeneratorPostProcessing
  src/main/java/graphql/schema/idl/RuntimeWiring.java
  src/main/java/graphql/schema/idl/SchemaGenerator.java
  src/main/java/graphql/schema/idl/SchemaGeneratorPostProcessing.java
  src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
Labels: breaking change

#3517 Removed deprecated methods in ValidationError
  src/main/java/graphql/validation/ValidationError.java
Labels: breaking change

#3494 Made the field definition lookup more optimised
  src/main/java/graphql/analysis/NodeVisitorWithTypeTracking.java
  src/main/java/graphql/execution/ExecutionStrategy.java
  src/main/java/graphql/introspection/Introspection.java
  src/main/java/graphql/normalized/ExecutableNormalizedOperationFactory.java
Labels: performance

#3514 Removed deprecated methods in code registry
  src/main/java/graphql/schema/GraphQLCodeRegistry.java
Labels: breaking change

#3490 Reduce the usage of CompletableFutures in graphql-java - now with objects
  src/main/java/graphql/execution/ExecutionStrategy.java
  src/main/java/graphql/execution/FieldValueInfo.java
  src/main/java/graphql/execution/incremental/DeferredExecutionSupport.java
  src/main/java/graphql/normalized/ExecutableNormalizedOperationFactory.java
  src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy
  src/test/groovy/graphql/execution/MaterialisedAndPromisedObjectsTest.groovy
Labels: breaking change, performance
