Repository graphql-java/graphql-java, pull requests merged in 2024-11, with the labels that each got.

#3710 Avoid unnecessary String allocations in AstPrinter
  src/main/java/graphql/language/AstPrinter.java
  src/main/java/graphql/util/EscapeUtil.java
Labels: performance

#3739 Remove SDLExtensionDefinition from InterfaceTypeDefinition
  src/main/java/graphql/language/InterfaceTypeDefinition.java
  src/main/java/graphql/language/InterfaceTypeExtensionDefinition.java
Labels: breaking change

#3749 Add test result comment bot
  .github/workflows/master.yml
  .github/workflows/pull_request.yml
Labels: not release related

#3753 Filter out negative line and column error locations in toSpecification
  src/main/java/graphql/GraphqlErrorHelper.java
  src/test/groovy/graphql/GraphQLErrorTest.groovy
Labels: breaking change
