Repository graphql-java/graphql-java, pull requests merged in 2025-04, with the labels that each got.

#3871 New spec validation: Subscriptions root field must not contain @skip nor @include on root selection set
  src/main/java/graphql/validation/ValidationErrorType.java
  src/main/java/graphql/validation/Validator.java
  src/main/java/graphql/validation/rules/SubscriptionRootField.java
  src/main/resources/i18n/Validation.properties
  src/main/resources/i18n/Validation_de.properties
  src/main/resources/i18n/Validation_nl.properties
  src/test/groovy/graphql/validation/rules/SubscriptionRootFieldNoSkipNoIncludeTest.groovy
  src/test/groovy/graphql/validation/rules/SubscriptionRootFieldTest.groovy
Labels: breaking change, spec-change

#3876 Track Engine sync code execution
  src/main/java/graphql/execution/AbstractAsyncExecutionStrategy.java
  src/main/java/graphql/execution/AsyncExecutionStrategy.java
  src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
  src/main/java/graphql/execution/EngineRunningObserver.java
  src/main/java/graphql/execution/Execution.java
  src/main/java/graphql/execution/ExecutionContext.java
  src/main/java/graphql/execution/ExecutionContextBuilder.java
  src/main/java/graphql/execution/ExecutionStrategy.java
  src/main/java/graphql/execution/SubscriptionExecutionStrategy.java
  src/test/groovy/graphql/EngineRunningTest.groovy
  src/test/groovy/graphql/execution/ExecutionContextBuilderTest.groovy
Labels: breaking change

#3869 Detect and prohibit new Guava classes
  build.gradle
  src/test/groovy/graphql/GuavaLimitCheck.groovy
Labels: not release related

#3867 Performance pipeline improvements
  .github/workflows/commit_performance_result.yml
  .github/workflows/publish_commit.yml
Labels: not release related

#3883 remove ExecutorInstrumentation and test
  src/main/java/graphql/execution/instrumentation/threadpools/ExecutorInstrumentation.java
  src/test/groovy/graphql/execution/instrumentation/threadpools/ExecutorInstrumentationTest.groovy
Labels: breaking change

#3866 Remove older GCP performance testing code
  .github/workflows/create_job.js
  .github/workflows/invoke_test_runner.yml
Labels: not release related

#3900 upgrade to gradle 8.13
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: not release related

#3943 avoid wrapping materialized fieldValueObject in a CompletableFuture
  src/main/java/graphql/execution/ExecutionStrategy.java
Labels: performance
